# Generated by Django 4.0.1 on 2022-01-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin')], default='User', max_length=100),
        ),
    ]
